version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3006:3006'
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - config.env.local
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.24
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: app
      MYSQL_PASSWORD: test1234
    volumes:
      - dbdata:/var/lib/mysql
    command: --innodb-buffer-pool-size=512M --max-connections=1000 --wait-timeout=28800 --default-authentication-plugin=mysql_native_password

#Volumes
volumes:
  dbdata:
    driver: local
